# Preprocessing script to remove duplicate learner_id rows from the combined
# file of enrolment files generated by the previous pre-processing script

enrol = allfiles[!duplicated(allfiles$learner_id), ]
repeated = allfiles[duplicated(allfiles$learner_id),]
enrolcount = nrow(enrol)
repeatedcount = nrow(repeated)
allcount = nrow(allfiles)

#convert the enrolled_at column of characters to a new date formatted column, calculate duration
enrol$enroldate = as.POSIXct(c(enrol$enrolled_at))
enrol$enroldate = as.Date(enrol$enroldate)
firststudent = min(enrol$enroldate)
laststudent = max(enrol$enroldate)
coursedurationdays = difftime(laststudent, firststudent, units = "day")
coursedurationweeks = difftime(laststudent, firststudent, units = "weeks")

#generate a date that can be used within text in an RMarkdown report
firststudentreport <- format(firststudent, format = "%d %B %Y")
laststudentreport <- format(laststudent,format = "%d %B %Y")

#unique count for each survey
cyber1unique = filter(enrol, survey == 1)
count1unique = nrow(cyber1unique)
cyber2unique = filter(enrol, survey == 2)
count2unique = nrow(cyber2unique)
cyber3unique = filter(enrol, survey == 3)
count3unique = nrow(cyber3unique)
cyber4unique = filter(enrol, survey == 4)
count4unique = nrow(cyber4unique)
cyber5unique = filter(enrol, survey == 5)
count5unique = nrow(cyber5unique)
cyber6unique = filter(enrol, survey == 6)
count6unique = nrow(cyber6unique)
cyber7unique = filter(enrol, survey == 7)
count7unique = nrow(cyber7unique)

#identify first and last student enrolment date for each intake when duplicates
#have been removed, calculate duration for each course in days, generate dates
#that can be used within text in an RMarkdown report
cyber1firststudentunique = min(cyber1unique$enroldate)
cyber1laststudentunique = max(cyber1unique$enroldate)
cyber1durationdaysunique = difftime(cyber1laststudentunique, cyber1firststudentunique, units = "day")
cyber1firststudentreport <- format(cyber1firststudentunique, format = "%d %B %Y")
cyber1laststudentreport <- format(cyber1laststudentunique,format = "%d %B %Y")

cyber2firststudentunique = min(cyber2unique$enroldate)
cyber2laststudentunique = max(cyber2unique$enroldate)
cyber2durationdaysunique = difftime(cyber2laststudentunique, cyber2firststudentunique, units = "day")
cyber2firststudentreport <- format(cyber2firststudentunique, format = "%d %B %Y")
cyber2laststudentreport <- format(cyber2laststudentunique,format = "%d %B %Y")

cyber3firststudentunique = min(cyber3unique$enroldate)
cyber3laststudentunique = max(cyber3unique$enroldate)
cyber3durationdaysunique = difftime(cyber3laststudentunique, cyber3firststudentunique, units = "day")
cyber3firststudentreport <- format(cyber3firststudentunique, format = "%d %B %Y")
cyber3laststudentreport <- format(cyber3laststudentunique,format = "%d %B %Y")

cyber4firststudentunique = min(cyber4unique$enroldate)
cyber4laststudentunique = max(cyber4unique$enroldate)
cyber4durationdaysunique = difftime(cyber4laststudentunique, cyber4firststudentunique, units = "day")
cyber4firststudentreport <- format(cyber4firststudentunique, format = "%d %B %Y")
cyber4laststudentreport <- format(cyber4laststudentunique,format = "%d %B %Y")

cyber5firststudentunique = min(cyber5unique$enroldate)
cyber5laststudentunique = max(cyber5unique$enroldate)
cyber5durationdaysunique = difftime(cyber5laststudentunique, cyber5firststudentunique, units = "day")
cyber5firststudentreport <- format(cyber5firststudentunique, format = "%d %B %Y")
cyber5laststudentreport <- format(cyber5laststudentunique,format = "%d %B %Y")

cyber6firststudentunique = min(cyber6unique$enroldate)
cyber6laststudentunique = max(cyber6unique$enroldate)
cyber6durationdaysunique = difftime(cyber6laststudentunique, cyber6firststudentunique, units = "day")
cyber6firststudentreport <- format(cyber6firststudentunique, format = "%d %B %Y")
cyber6laststudentreport <- format(cyber6laststudentunique,format = "%d %B %Y")

cyber7firststudentunique = min(cyber7unique$enroldate)
cyber7laststudentunique = max(cyber7unique$enroldate)
cyber7durationdaysunique = difftime(cyber7laststudentunique, cyber7firststudentunique, units = "day")
cyber7firststudentreport <- format(cyber7firststudentunique, format = "%d %B %Y")
cyber7laststudentreport <- format(cyber7laststudentunique,format = "%d %B %Y")

#Other calculations
course_numbers = summary(enrol$survey)
